name: time_tracker

description: A Dart object that records time-status changes and can be started,
  paused, resumed, and ended.

version: 1.1.0

homepage: https://github.com/simphotonics/time_tracker

environment:
  sdk: ^3.0.0
  
dependencies:
  serialize_enum: ^0.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
