name: time_tracker

description: A Dart object that remembers its instantiation time.

version: 1.0.0

homepage: https://github.com/simphotonics/time_tracker

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  stride: ^1.0.0
